language: node_js

cache:
    directories:
        - node_modules
        - $NVM_DIR

node_js:
  - v6

env:
  - FB_PAGE_TOKEN=EAAEsqAqZAD7EBAKZC4z8sXjP6xMrPsFRHgJ7vqDpJywW4rhDchITMXnqK0BITff7pR0me6rybchUqZAp1ZB9TfO0gJhqho479i4twNgcxrGXJ845lPG5dAYGUlBHz2Rq86sgZAhUfPVkG2f0uwjaCgHQO6FfGF2bwrFJuaTy3iAZDZD \
    FB_APP_SECRET=e608f82d4c4c6267b0d1994a251df8c5 \
    WIT_TOKEN=NFEBDIRJOFPTEH6XNIRUPTYL4P3FW627
